### ISSUE TITLE
 obs page cannot be opened

### ISSUE THREAD

**Issue by shafeipaozi** [markyangcc/markyangcc.github.io#5]
Hello, I saw the personal deployment of obs on your personal blog. I have been doing it recently, but I configured the service and used the iso image to start it, but I cannot open the local host and see the obs page. Can you please help me?

**Comment by markyangcc** [comment]
curl 80 和 443 端口有返回吗

Example:
```shell
curl  [obs-server-ip]:80
curl  [obs-server-ip]:443
```

**Comment by shafeipaozi** [comment]
> curl 80 和 443 端口有返回吗
> 
> Example:
> 
> ```shell
> curl  [obs-server-ip]:80
> curl  [obs-server-ip]:443
> ```
Thanks for the reply, the results after execution are as follows:
reply
curl: (7) Failed to connect to 10.100.4.13 port 80 after 0 ms: Couldn't connect to server
curl: (7) Failed to connect to 10.100.4.13 port 443 after 0 ms: Couldn't connect to server
(I use the iso boot image myself. Logically speaking, it should be accessible after booting, but mine is a server)

**Comment by markyangcc** [comment]
有 VNC 吗，用 VNC 连进去，curl localhost:80/443 端口有返回吗。obs-server ssh 服务是关的，只能用 VNC 连

**Comment by shafeipaozi** [comment]
> 有 VNC 吗，用 VNC 连进去，curl localhost:80/443 端口有返回吗。obs-server ssh 服务是关的，只能用 VNC 连

我用的mobaxterm,等下我试一下vnc,我在服务器本地装了Firefox，用Firefox打开local host也不行。

**Comment by markyangcc** [comment]
> > 有 VNC 吗，用 VNC 连进去，curl localhost:80/443 端口有返回吗。obs-server ssh 服务是关的，只能用 VNC 连
> 
> 我用的mobaxterm,等下我试一下vnc,我在服务器本地装了Firefox，用Firefox打开local host也不行。

需要检查下 apache2 服务是否已经启动。允许重启机器的话，先重启试下

**Comment by shafeipaozi** [comment]
> > > 有 VNC 吗，用 VNC 连进去，curl localhost:80/443 端口有返回吗。obs-server ssh 服务是关的，只能用 VNC 连
> > 
> > 
> > 我用的mobaxterm,等下我试一下vnc,我在服务器本地装了Firefox，用Firefox打开local host也不行。
> 
> 需要检查下 apache2 服务是否已经启动。允许重启机器的话，先重启试下

apache2服务这里，我第一次打开的时候能够访问80端口，但是只有两行字介绍obs，443拒绝连接，关机后现在打开两个端口都打不开了，同时apache2挂了，我查了日志发现缺少很多模块，经过各种安装并且给配置文件的问题行打#，才解决让apache2重启，但是依然无法打开端口访问网页。

**Comment by markyangcc** [comment]
> > > > 有 VNC 吗，用 VNC 连进去，curl localhost:80/443 端口有返回吗。obs-server ssh 服务是关的，只能用 VNC 连
> > > 
> > > 
> > > 我用的mobaxterm,等下我试一下vnc,我在服务器本地装了Firefox，用Firefox打开local host也不行。
> > 
> > 
> > 需要检查下 apache2 服务是否已经启动。允许重启机器的话，先重启试下
> 
> apache2服务这里，我第一次打开的时候能够访问80端口，但是只有两行字介绍obs，443拒绝连接，关机后现在打开两个端口都打不开了，同时apache2挂了，我查了日志发现缺少很多模块，经过各种安装并且给配置文件的问题行打#，才解决让apache2重启，但是依然无法打开端口访问网页。

这个问题应该不是 apache2 的问题，apache2.service 开机时 enable 的，不需要手动重启。应该还是 fqdn 的问题，需要 10min 后才能启动后续服务。
看这里介绍尝试修改下，在试下  https://markyangcc.github.io/run-your-own-obs-open-build-service/#%E9%85%8D%E7%BD%AE:~:text=/usr/lib/obs/server/setup%2Dappliance.sh

`journalctl -f` 展示 apach2 服务没启动是因为尝试获取 fqdn

**Comment by shafeipaozi** [comment]
> > > > > 有 VNC 吗，用 VNC 连进去，curl localhost:80/443 端口有返回吗。obs-server ssh 服务是关的，只能用 VNC 连
> > > > 
> > > > 
> > > > 我用的mobaxterm,等下我试一下vnc,我在服务器本地装了Firefox，用Firefox打开local host也不行。
> > > 
> > > 
> > > 需要检查下 apache2 服务是否已经启动。允许重启机器的话，先重启试下
> > 
> > 
> > apache2服务这里，我第一次打开的时候能够访问80端口，但是只有两行字介绍obs，443拒绝连接，关机后现在打开两个端口都打不开了，同时apache2挂了，我查了日志发现缺少很多模块，经过各种安装并且给配置文件的问题行打#，才解决让apache2重启，但是依然无法打开端口访问网页。
> 
> 这个问题应该不是 apache2 的问题，apache2.service 开机时 enable 的，不需要手动重启。应该还是 fqdn 的问题，需要 10min 后才能启动后续服务。 看这里介绍尝试修改下，在试下 https://markyangcc.github.io/run-your-own-obs-open-build-service/#%E9%85%8D%E7%BD%AE:~:text=/usr/lib/obs/server/setup%2Dappliance.sh
> 
> `journalctl -f` 展示 apach2 服务没启动是因为尝试获取 fqdn

大佬，我在你的个人博客有留言，看到过你写的，我将时间也修改到了60秒....

**Comment by markyangcc** [comment]
现在架构是 obs-server 在虚拟机里，还是安装在 host 上

进去 obs-server 的机器里，curl https://localhost:443 , 有返回吗, 加上 `https://` 前缀以及端口号

**Comment by shafeipaozi** [comment]
> 现在架构是 obs-server 在虚拟机里，还是安装在 host 上
> 
> 进去 obs-server 的机器里，curl https://localhost:443 , 有返回吗, 加上 `https://` 前缀以及端口号

现在我是在服务器里面装的iso镜像起来了，然后配置了哪些服务，包括obs-server
输入
curl https://localhost:443,
回复 
curl: (7) Failed to connect to localhost port 443 after 0 ms: Couldn't connect to server
等下准备重启一个新环境，重头做一下，大佬方便加个联系方式吗？
（wx同我的github的ID）

**Comment by markyangcc** [comment]
> > 现在架构是 obs-server 在虚拟机里，还是安装在 host 上
> > 进去 obs-server 的机器里，curl https://localhost:443 , 有返回吗, 加上 `https://` 前缀以及端口号
> 
> 现在我是在服务器里面装的iso镜像起来了，然后配置了哪些服务，包括obs-server 输入 curl https://localhost:443, 回复 curl: (7) Failed to connect to localhost port 443 after 0 ms: Couldn't connect to server 等下准备重启一个新环境，重头做一下，大佬方便加个联系方式吗？ （wx同我的github的ID）

看起来确实是有问题
